### ISSUE TITLE
Is this compatible with tensor flow?

### ISSUE THREAD

**Issue by NullVoxPopuli** [reicek/NeatapticTS#3]
I've been looking for a reinforcement learning library to use with tensor flow (it's quite difficult!), And am wondering if this one is compatible?

Tensor flow has gpu acceleration, which is great for training large neural networks in the browser (2^13 neurons)

**Comment by reicek** [comment]
Hi @NullVoxPopuli !
This library is not compatible with TensorFlow. Neataptic has it's own implementation for neural networks. 

It's extremely easy to use, why don't you give it a try? You can read more about how to use it on the original repo: https://github.com/wagenaartje/neataptic

The idea of this repo is to update the original library to TypeScript. Hopefully it will be ready at some point on 2021.

**Comment by reicek** [comment]
Opened #4 to backlog GPU acceleration support.
